import type { Metadata } from 'next';
import { LegalPage, Section, Term, Bullets, Ext } from '@/components/legal/LegalPage';

export const metadata: Metadata = {
  title: 'Terms & Conditions · Vikas 75',
  description: 'The simple rules for playing Vikas 75 — a free party game about Indian government schemes.',
};

const LAST_UPDATED = '24 August 2026';

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      lastUpdated={LAST_UPDATED}
      intro={
        <>
          <strong style={{ color: '#fff' }}>The short version.</strong> Vikas 75 is a free party game
          made to make learning about government schemes fun. Play fair, be kind to other players,
          and remember the verdicts are for entertainment — the best answer isn&apos;t always right.
          Using the game means you accept these terms.
        </>
      }
    >
      <Section n={1} title="Acceptance of these terms">
        <p>
          By hosting or joining a game of Vikas 75 (&ldquo;the game&rdquo;), you agree to these Terms
          &amp; Conditions and to our{' '}
          <a href="/privacy" style={{ color: '#FF9933', textDecoration: 'none', borderBottom: '1px solid rgba(255,153,51,0.4)' }}>Privacy Policy</a>.
          If you don&apos;t agree, please don&apos;t use the game.
        </p>
      </Section>

      <Section n={2} title="What Vikas 75 is">
        <p>
          Vikas 75 is a free, multiplayer card game about Indian government schemes, run as an
          initiative of the Office of Sujeet Kumar for public events, campuses, and workshops. It is
          made for <Term>education and entertainment</Term>. It is an independent initiative and is{' '}
          <Term>not an official service of the Government of India</Term> or of any government
          department, and is not affiliated with or endorsed by them unless expressly stated.
        </p>
      </Section>

      <Section n={3} title="Who can play">
        <p>
          The game is meant for general audiences. There are no accounts — you join with a nickname.
          If you are under 18, please play with a parent or guardian&apos;s involvement. Do not enter
          real personal details about yourself or anyone else, and do not submit another
          person&apos;s information.
        </p>
      </Section>

      <Section n={4} title="How a game works">
        <p>
          One person hosts and drives the game; players join from their phones with a room code; a
          shared screen shows the public view. Each round shows a challenge, players pick a scheme
          card and argue their case, and an AI judge picks a winner. The host can adjust settings,
          remove a player, or end the game at any time, and game rooms are temporary — they close
          automatically.
        </p>
      </Section>

      <Section n={5} title="Your content">
        <p>
          You keep ownership of the name, explanations, and chat messages you submit. By submitting
          them you grant us a limited, non-exclusive licence to display them to other participants
          and on the shared screen for the purpose of running that game. You are responsible for what
          you submit, and you confirm it is lawful and yours to share.
        </p>
      </Section>

      <Section n={6} title="Fair and respectful play">
        <p>When you play, you agree not to:</p>
        <Bullets
          items={[
            'Harass, threaten, demean, or discriminate against other players.',
            'Submit content that is unlawful, hateful, obscene, or infringes someone&apos;s rights.',
            'Impersonate another person, or enter other people&apos;s personal data.',
            'Cheat, disrupt a game, abuse the AI judge, or interfere with other players&apos; experience.',
            'Attempt to break, overload, scrape, reverse-engineer, or gain unauthorised access to the game or its systems.',
          ]}
        />
        <p>
          We filter obvious profanity automatically, but we can&apos;t review everything. A host may
          remove a player, and we may restrict access, to keep a game safe and fair.
        </p>
      </Section>

      <Section n={7} title="The AI judge">
        <p>
          Verdicts are generated by an AI (or, when unavailable, a random fallback) and are{' '}
          <Term>subjective, imperfect, and purely for entertainment</Term>. They are not statements
          of fact and carry no real-world weight. As the game likes to say: the best answer
          isn&apos;t always right.
        </p>
      </Section>

      <Section n={8} title="About the scheme information">
        <p>
          The scheme and challenge cards are meant to spark interest and conversation. They are
          simplified for play and may be incomplete or out of date, and they are not official
          government communications or advice. For accurate, current details about any scheme, always
          rely on official sources such as{' '}
          <Ext href="https://www.myscheme.gov.in/">myscheme.gov.in</Ext> and{' '}
          <Ext href="https://www.india.gov.in/">india.gov.in</Ext>.
        </p>
      </Section>

      <Section n={9} title="Intellectual property">
        <p>
          The Vikas 75 name, branding, game design, software, and card artwork belong to the Office
          of Sujeet Kumar and its licensors, and are protected by law. Factual information about
          public government schemes is, of course, public. You may play and share the game as
          intended, but you may not copy, resell, or create derivative products from our materials
          without permission.
        </p>
      </Section>

      <Section n={10} title="Third-party services">
        <p>
          The game relies on third-party providers (including Upstash, Pusher, Anthropic, and Vercel)
          to run. Their handling of data is covered in our{' '}
          <a href="/privacy" style={{ color: '#FF9933', textDecoration: 'none', borderBottom: '1px solid rgba(255,153,51,0.4)' }}>Privacy Policy</a>,
          and their own terms may also apply.
        </p>
      </Section>

      <Section n={11} title="Availability, and &ldquo;as is&rdquo;">
        <p>
          The game is provided <Term>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</Term>,
          without warranties of any kind. We may change, suspend, or discontinue any part of it at
          any time, and we don&apos;t promise it will always be available, uninterrupted, or
          error-free.
        </p>
      </Section>

      <Section n={12} title="Limitation of liability">
        <p>
          To the fullest extent permitted by law, the Office of Sujeet Kumar and the makers of Vikas
          75 will not be liable for any indirect, incidental, or consequential loss arising from your
          use of the game. Nothing in these terms limits any liability that cannot be limited under
          applicable law.
        </p>
      </Section>

      <Section n={13} title="Changes to these terms">
        <p>
          We may update these terms from time to time. When we do, we&apos;ll change the &ldquo;last
          updated&rdquo; date above. Continuing to play after a change means you accept the updated
          terms.
        </p>
      </Section>

      <Section n={14} title="Governing law">
        <p>
          These terms are governed by the laws of India, and the courts of{' '}
          <Term>[add your city/jurisdiction]</Term> will have jurisdiction over any dispute, subject
          to applicable law.
        </p>
      </Section>

      <Section n={15} title="Contact">
        <p>
          Questions about these terms? Reach the Office of Sujeet Kumar via{' '}
          <Ext href="https://www.sujeetkofficial.com/">sujeetkofficial.com</Ext> or by email at{' '}
          <Term>[add your contact email]</Term>.
        </p>
      </Section>
    </LegalPage>
  );
}
